name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # UTC
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Checkout fork repo
      - name: Checkout target repo
        uses: actions/checkout@v4

      # Run the sync action
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        continue-on-error: true
        with:
          upstream_sync_repo: ling-drag0n/CloudPaste
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
          
      # Telegram notify on successful sync with new commits
      - name: Telegram notify - Sync success with updates
        if: steps.sync.outputs.has_new_commits == 'true'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -H "Content-Type: application/json" \
            -d '{
                  "chat_id": "'${{ secrets.TELEGRAM_CHAT_ID }}'",
                  "text": "<b>✅ [Upstream Sync]</b>\nRepo: <b>${{ github.repository }}</b>\nBranch: main\n✔️ Sync successful.\nNew commits were pulled from upstream.",
                  "parse_mode": "HTML"
                }'
      
      # Telegram notify if sync step failed
      - name: Telegram notify - Sync failure
        if: steps.sync.outcome == 'failure'
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -H "Content-Type: application/json" \
            -d '{
                  "chat_id": "'${{ secrets.TELEGRAM_CHAT_ID }}'",
                  "text": "<b>❌ [Upstream Sync FAILED]</b>\nRepo: <b>${{ github.repository }}</b>\nBranch: main\n⚠️ The sync process failed. This might be due to upstream workflow changes or other errors. Please check and sync manually.",
                  "parse_mode": "HTML"
                }'


      # Check sync result
      - name: Sync check
        if: steps.sync.outcome == 'failure'
        run: |
          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions."
          exit 1
